baseURL = 'https://docs.roguerope.be/'
languageCode = 'en-us'
title = 'Rogue Rope Camp'
theme = 'hextra'
enableRobotsTXT = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[outputs]
  home = ["HTML", "RSS"]

[[menus.main]]
  identifier = "concept"
  name = "The Vibe"
  pageRef = "/docs/concept"
  weight = 1

[[menus.main]]
  identifier = "practical"
  name = "Practical"
  pageRef = "/docs/practical"
  weight = 2

[[menus.main]]
  identifier = "wellbeing"
  name = "Wellbeing"
  pageRef = "/docs/wellbeing"
  weight = 3

[[menus.main]]
  identifier = "tickets"
  name = "Tickets"
  pageRef = "/docs/practical/tickets"
  weight = 4

[[menus.main]]
  identifier = "contact"
  name = "Contact"
  pageRef = "/docs/contact"
  weight = 5

[[menus.main]]
  identifier = "search"
  weight = 98
  [menus.main.params]
    type = "search"

[[menus.main]]
  identifier = "theme-toggle"
  weight = 99
  [menus.main.params]
    type = "theme-toggle"

[params]
  displayUpdatedDate = true
  dateFormat = "January 2, 2006"

  [params.theme]
    default = "light"
    displayToggle = true

  [params.search]
    enable = true
    type = "flexsearch"

  [params.navbar]
    displayTitle = true
    displayLogo = true
    width = "wide"
    [params.navbar.logo]
      path = "images/logo-dark.svg"
      dark = "images/logo-dark.svg"
      width = 32
      height = 32

  [params.footer]
    enable = true
    displayCopyright = false
    displayPoweredBy = false
    width = "wide"

  [params.page]
    width = "wide"

  [params.imageZoom]
    enable = true

  [params.highlight]
    [params.highlight.copy]
      enable = true
      display = "hover"
